# Generated by Django 5.2.2 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('blurb', models.TextField(verbose_name='Краткое описание')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('usd_goal', models.FloatField(verbose_name='Финансовая цель (USD)')),
                ('campaign_days', models.IntegerField(verbose_name='Длина кампании (дни)')),
                ('prelaunch_activated', models.BooleanField(verbose_name='Предстартовая кампания активирована?')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('creation_time', models.TimeField(verbose_name='Время создания')),
                ('launch_date', models.DateField(verbose_name='Дата запуска')),
                ('launch_time', models.TimeField(verbose_name='Время запуска')),
                ('description', models.TextField(verbose_name='Текстовое описание')),
                ('images', models.TextField(blank=True, null=True, verbose_name='Ссылки на изображения')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
