# Generated by Django 5.2.2 on 2025-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_to_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение проекта'),
        ),
    ]
