# Generated by Django 5.2.2 on 2025-06-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_to_user', '0002_alter_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.TextField(blank=True, default='', verbose_name='Ссылки на изображения проекта (через запятую)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео '),
        ),
    ]
